#!/bin/bash
#$ENV{T_HIGH} || 1800
t_high=1800
t_med=500
t_low=250

#curl -s https://michael-crilly.com/projects/library/data/spaces/ > ~/.cache/durham-library
#seats=$(cat ~/.cache/durham-library)
seats=1800

echo -e $seats
echo
if [ $seats -le $t_low ]
then
    echo "#FF0000"
    exit 0
fi
if [ $seats -le $t_med ]
then
    echo "#FFFF00"
    exit 0
fi
if [ $seats -le $t_high ]
then
    echo "#00FF00"
    exit 0
fi
